 2018-10-12 09:54:21,160 [P11140/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.12.2 application starting on PRO00151
 2018-10-12 09:54:21,210 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-10-12 09:54:21,228 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 17ms)
 2018-10-12 09:54:21,341 [P11140/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-10-12 09:54:21,346 [P11140/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-10-12 09:54:21,353 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-10-12 09:54:21,459 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 106ms)
 2018-10-12 09:54:21,460 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-10-12 09:54:21,462 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 2ms)
 2018-10-12 09:54:21,507 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-10-12 09:54:21,509 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2018-10-12 09:54:21,510 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-10-12 09:54:21,510 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2018-10-12 09:54:21,512 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-10-12 09:54:21,512 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-10-12 09:54:21,513 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-10-12 09:54:21,518 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 4ms)
 2018-10-12 09:54:21,574 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-10-12 09:54:21,574 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-10-12 09:54:21,575 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-10-12 09:54:21,576 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 1ms)
 2018-10-12 09:54:21,578 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-10-12 09:54:21,578 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-10-12 09:54:21,579 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-10-12 09:54:21,581 [P11140/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 2ms)
 2018-10-12 09:54:24,866 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:24,893 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:25,179 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:25,191 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:26,425 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:26,431 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:27,614 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:27,623 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:28,765 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:28,780 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:29,895 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:29,920 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:31,061 [P11140/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\Umbraco.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2018-10-12 09:54:31,066 [P11140/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-10-12 09:54:31,093 [P11140/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   at Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
 2018-10-12 09:54:41,168 [P11140/D2/T13] INFO  Umbraco.Core.MainDom - Stopping...
 2018-10-12 09:54:41,169 [P11140/D2/T13] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2018-10-12 09:54:41,283 [P11140/D2/T13] ERROR Umbraco.Web.ExamineStartup - The index InternalIndexer is rebuilding due to being unreadable/corrupt
System.IO.FileNotFoundException: Could not find file 'C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\TEMP\ExamineIndexes\Internal\Index\_1t.cfs'.
File name: 'C:\Users\tertia.southwick\Source\Repos\TertiaSite\TertiaUmbraco\App_Data\TEMP\ExamineIndexes\Internal\Index\_1t.cfs'
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.DirectoryReader.Open(Directory directory, IndexDeletionPolicy deletionPolicy, IndexCommit commit, Boolean readOnly, Int32 termInfosIndexDivisor)
   at Lucene.Net.Index.IndexReader.Open(Directory directory, Boolean readOnly)
   at Examine.LuceneEngine.Providers.LuceneIndexer.IsReadable(Exception& ex) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 961
 2018-10-12 09:54:41,297 [P11140/D2/T13] INFO  Umbraco.Web.ExamineStartup - Complete (took 128ms)
 2018-10-12 09:54:41,298 [P11140/D2/T13] INFO  Umbraco.Core.MainDom - Released MainDom.
